networks:
  public:
    external: true
    name: public
  quantum-custom-metrics:
    name: quantum-custom-metrics
    external: true
services:
  opentripplanner:
    deploy:
      labels:
        com.planetary-quantum.metrics.custom: opentripplanner_production
        com.planetary-quantum.metrics.custom.path: /otp/actuators/prometheus
        com.planetary-quantum.metrics.custom.port: 8080
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: Host:api.angermuende.bbnavi.de,api.bbnavi.de
        traefik.port: '8080'
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi
      replicas: 1
    environment:
      API_URL: https://api.bbnavi.de/otp/
      OTP_PORT: '8090'
      MEMORY: '24G'
    healthcheck:
      interval: 15s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/
      timeout: 10s
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/opentripplaner-berlin-brandenburg:production
    networks:
      public: {}
      quantum-custom-metrics: {}
version: '3.7'
